### ISSUE TITLE
No module named chess

### ISSUE THREAD

**Issue by yhyu13** [Zeta36/chess-alpha-zero#1]
@Zeta36 

When I run ```python src/chess_zero/run.py self``` under root, it says:
```
Traceback (most recent call last):
  File "src/chess_zero/run.py", line 16, in <module>
    from chess_zero import manager
  File "src/chess_zero/manager.py", line 6, in <module>
    from .config import Config
  File "src/chess_zero/config.py", line 2, in <module>
    import chess
ModuleNotFoundError: No module named 'chess'
```
Is there any python module named ```chess```?

**Comment by yhyu13** [comment]
@Zeta36 

Also, i am having trouble installing wxpython in pip. I tried it in conda install but conda only has the py2.7 version.

**Comment by Zeta36** [comment]
@yhyu13 wxpython  it is not important. The module of ches is pip install python-chess: https://pypi.python.org/pypi/python-chess

**Comment by yhyu13** [comment]
@Zeta36 
Solved. Up and running.
