### ISSUE TITLE
logger isn't substituting values

### ISSUE THREAD

**Issue by Akababa** [Zeta36/chess-alpha-zero#22]
For example this is what I get:
`2017-12-13 09:38:11,484@chess_zero.agent.model_chess DEBUG # model files does not exist at {config_path} and {weight_path}`
`2017-12-13 09:38:12,425@chess_zero.agent.model_chess DEBUG # save model to {config_path}`
`2017-12-13 09:38:13,099@chess_zero.agent.model_chess DEBUG # saved model digest {self.digest}`

IDK if I'm missing something here, but I don't think logger has access to the calling scope.

**Comment by bame55** [comment]
The python "f" specifier for strings was introduced in python 3.6 based on PEP 498 (https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498).  In other words, those f prefixes on strings were not typos or errors of any sort.  Unfortunately pull request #21 got rid of all the "f" string prefixes, which means variable substitution for strings sent to logger no longer works.  For folks with python < 3.6 there are other ways to handle the lack of support for "f" strings, but just removing the "f" is not one of them.

**Comment by Akababa** [comment]
My bad, it looks like windows is a no-go until TF supports python3.6 then.

**Comment by bame55** [comment]
It should be simple to rewrite all the "f" strings for python < 3.6.  There are many ways to do it, including the "format" method, which does exactly the same as the "f" prefix.  Here's a good summary: https://pyformat.info/

**Comment by Akababa** [comment]
Yeah that's what I've been doing (printf-style), but since the repo is 3.6 I can just use WSL to make things easier for everyone else

**Comment by Zeta36** [comment]
I can deploy in Windows using python3.6 and "f" strings so I wrote back all "f" in the project.
