### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by Linus789** [Zeta36/chess-alpha-zero#35]
Traceback (most recent call last):
  File "src/chess_zero/run.py", line 17, in <module>
    from chess_zero import manager
  File "src/chess_zero/manager.py", line 22
    def setup(config: Config, args):
                    ^
SyntaxError: invalid syntax

**Comment by Akababa** [comment]
What's your python version? `python -V`

**Comment by Linus789** [comment]
linus@Linus-desktop ~/AlphaZero $ sudo python3 src/chess_zero/run.py self
>Traceback (most recent call last):
>  File "src/chess_zero/run.py", line 17, in <module>
>    from chess_zero import manager
>  File "src/chess_zero/manager.py", line 41
>    logger.info(f"config type: {config_type}")
                                            ^
SyntaxError: invalid syntax
linus@Linus-desktop ~/AlphaZero $ python3 -V
>Python 3.5.2

**Comment by brianprichardson** [comment]
Python 3.6.3 is required

**Comment by Linus789** [comment]
ok thx :)
