### ISSUE TITLE
Not bugs, just questions about designing.

### ISSUE THREAD

**Issue by PlanetMoon** [Zeta36/chess-alpha-zero#42]
Hi, Zeta36!

I am trying to construct an alpha-zero-style AI for Twelve Shogi, a simple kind of Shogi. I am wondering that how you designed the board state for CNN input.

Thanks.

**Comment by RavnaBergsndot** [comment]
Check this function in chess_env.py:

https://github.com/Zeta36/chess-alpha-zero/blob/master/src/chess_zero/env/chess_env.py#L290

**Comment by Akababa** [comment]
I wrote a short description [here](https://github.com/Akababa/Chess-Zero/wiki#model-diagram), also you might find page 13 of [DeepMind's paper](https://arxiv.org/pdf/1712.01815.pdf) useful.

**Comment by PlanetMoon** [comment]
Thanks for @RavnaBergsndot and @Akababa . I think I have got it.
