### ISSUE TITLE
Optimal self-play ?

### ISSUE THREAD

**Issue by glennsamuel32** [Zeta36/chess-alpha-zero#49]
Congrats on this amazing project !!
How many games or hours are advisable for a good learning experience in Self-Play ?
50 games took 21 min on my laptop using a GTX 950M -- would that be an acceptable speed ?

**Comment by Zeta36** [comment]
DeepMind model played about 300.000 self-games so...you would need near a year to reach its level. That's the problem in my opinion with the AlphaZero approach, it needs a so huge amount of hardware that it's very hard to replicate it by the free source community. 

In fact, there exists a distributed version of this project (in C++) here: https://github.com/glinscott/leela-chess

It's very possible that this project, if get enough support, could reach an aceptable level of game with a thousands (maybe hundreds can be enough) of clients contributing GPU power at the same time.

Take a look! ;)
